import type { Metadata } from "next";
import "./globals.css";
import { ClerkThemeWrapper, ThemeProvider } from "@/components/theme-provider";

import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClerkThemeWrapper>
            <Header />
            <main className="container mx-auto">{children}</main>
          </ClerkThemeWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
